/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: jemepousse (https://sketchfab.com/jemepousse)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/356c773c4b9a45d8b9d4aa04c60ecb27
title: Red City
*/

import * as THREE from 'three'
import React, { useRef, useEffect, useState } from 'react'
import { useLoader, useFrame, useThree } from '@react-three/fiber'
import { useGLTF, Edges } from '@react-three/drei'

export default function LulabyCityModel(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('./textures/scene-draco.glb')
    useFrame(() => (group.current.rotation.y += 0.0002))
    return (
        <group ref={group} scale={[0.002, 0.002, 0.002]} position={[0, 0, -100]} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[-102253.52, -210688.86, -11050.52]}>
                    <mesh material={materials.Scene_Root} geometry={nodes.mesh_0.geometry} >
                        <Edges scale={1} color="#fff" />
                    </mesh>
                    <mesh material={materials.Scene_Root} geometry={nodes.mesh_1.geometry} >
                        <Edges scale={1} color="#fff" />
                    </mesh>
                    <mesh material={materials.Scene_Root} geometry={nodes.mesh_2.geometry} >
                        <Edges scale={1} color="#fff" />
                    </mesh>
                    <mesh material={materials.Scene_Root} geometry={nodes.mesh_3.geometry} >
                        <Edges scale={1} color="#fff" />
                    </mesh>
                </group>
                <mesh position={[250000, -200000, 50000]}>
                    <sphereBufferGeometry attach="geometry" args={[30000, 32, 32]} />
                    <meshBasicMaterial attach="material" color="#0200f2" />
                </mesh>
            </group>
        </group>
    )
}

// #ff1000 - red